# ASSIGNMENT

1. Create a 4x4 matrix with values ranging from 0 to 3.\
(The following image is just as an example. It doesn't represent the real image of arrays in the question)
![](image/assignment2.png)

Answer:

In [16]:
import numpy as np
from numpy import random
import math

matriks4x4 = np.zeros((4,4))
print("Create 4x4 Matrix with zero values")
print(matriks4x4)
print("-----------------------------------")
print("Change values ranging from 0 to 3")
matriks4x4 += np.arange(4)
print(matriks4x4)

Create 4x4 Matrix with zero values
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----------------------------------
Change values ranging from 0 to 3
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.\
![](image/assignment.png)

Answer

In [15]:
matriks = np.arange(0, 16).reshape(4,4)
print("Original Matriks 4x4:")
print(matriks)
matriks = np.hsplit(matriks,2)
print("-----------------------------------")
print("Split into 2 arrays:")
print(" ")
print("Data split 1")
print(matriks[0])
print(" ")
print("Data split 2")
print(matriks[1])

Original Matriks 4x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
-----------------------------------
Split into 2 arrays:
 
Data split 1
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
 
Data split 2
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Answer:

In [38]:
def is_prime(n):
    if n % 2 == 0 and n > 2 or (n == 0 or n == 1) : 
        return False
    return all(n % i for i in range(3, int(math.sqrt(n)) + 1, 2))

array = np.arange(1, 26).reshape(5,5)
foo = np.vectorize(is_prime)
pbools = foo(array)
primes = np.extract(pbools, array)

print("Array yang dimiliki (sebelum difilter):") 
print(array) 
print("----------------------------") 
print("Filtering mendapatkan bilangan prima:") 
print(primes)

Array yang dimiliki (sebelum difilter):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
----------------------------
Filtering mendapatkan bilangan prima:
[ 2  3  5  7 11 13 17 19 23]
